Repository catchroom/FE_CatchRoom, pull requests merged in 2023-12, with the labels that each got.

#3 Chore : 필요한 라이브러리 설치
  api/fetch-text.ts
  app/home/page.tsx
  components/common/provider/provider.tsx
  package-lock.json
  package.json
  pages/api/testing/get.ts
  utils/get-current-url.ts
Labels: enhancement

#6 Feat : middleware 설정
  amplify.yml
  api/fetch-text.ts
  app/home/page.tsx
  middleware.ts
  pages/api/bypass/get.ts
Labels: enhancement

#12 ✨feat : 공동 컴포넌트(버튼) 구현
  atoms/heartButton.ts
  atoms/toggleButton.ts
  components/common/heartButton/index.tsx
  components/common/toggleButton/index.tsx
  package-lock.json
  package.json
  tailwind.config.ts
Labels: feat

#15 ✨ feat: root layout 작성 pr
  app/globals.css
  app/home/page.tsx
  app/layout.tsx
  components/common/layoutTemplate/RootTemplate/index.tsx
  tailwind.config.ts
Labels: feat

#18 ✨ feat: 마이페이지 메인 화면 레이아웃 작성 feat
  app/globals.css
  app/mypage/page.tsx
  assets/fonts/PretendardVariable.woff2
  components/common/layoutTemplate/RootTemplate/index.tsx
  components/mypage/account/accountButton/index.tsx
  components/mypage/account/accountContainer/index.tsx
  components/mypage/banner/bannerContainer/index.tsx
  components/mypage/banner/bannerIcon/index.tsx
  components/mypage/banner/bannerItem/index.tsx
  components/mypage/profile/profileButton/index.tsx
  components/mypage/profile/profileContainer/index.tsx
  constants/mypage.ts
  tailwind.config.ts
Labels: feat, chore

#20 🐛 fix : fontSize 중첩 속성 제거 pr
  app/mypage/page.tsx
  constants/mypage.ts
  tailwind.config.ts
Labels: fix

#22 ✨ feat : 판매 페이지 레이아웃 구현
  app/sale/page.tsx
  components/common/provider/provider.tsx
  components/sale/catch/catchContainer/index.tsx
  components/sale/catch/catchDropDown/index.tsx
  components/sale/checkboxContainer/index.tsx
  components/sale/modal/index.tsx
  components/sale/price/index.tsx
  components/sale/saleEndContainer/index.tsx
  components/sale/saleInfoContainer/index.tsx
  components/sale/sellingPrice/sellingPriceBtn/index.tsx
  components/sale/sellingPrice/sellingPriceContainer/index.tsx
  package-lock.json
  package.json
  public/calendar.svg
  tailwind.config.ts
Labels: feat, style

#24 ✨ feat : 캐치특가 페이지 및 검색하기 페이지 레이아웃 제작 (+ 캐치특가 공동 컴포넌트)
  app/catchitems/page.tsx
  app/searchroom/page.tsx
  components/catchItems/header/bottomHeader/index.tsx
  components/catchItems/header/index.tsx
  components/catchItems/header/middleHeader/index.tsx
  components/catchItems/header/topHeader/index.tsx
  components/catchItems/items/index.tsx
  components/common/catchComponent/index.tsx
  components/common/heartButton/index.tsx
  components/common/selectBoxButton/index.tsx
  components/common/toggleButton/index.tsx
  components/searchroom/bodyComponent/footerComponent/index.tsx
  components/searchroom/bodyComponent/index.tsx
  components/searchroom/bodyComponent/searchComponent/index.tsx
  components/searchroom/headerComponent/index.tsx
  constants/catchItems.ts
  constants/serchpage.ts
  public/sample/room1.jpg
  public/sample/room2.jpg
  tailwind.config.ts
  types/common/catchItems/types.ts
  types/common/selectBoxButton/types.ts
Labels: feat, style

#26 ✨ feat : 헤더, 하단nav 제작
  components/common/bottomNav/index.tsx
  components/common/header/index.tsx
  public/svg/chevron-left.svg
  public/svg/dots-vertical.svg
  public/svg/ph_x.svg
  types/common/types.ts
Labels: feat
