Repository catchroom/FE_CatchRoom, pull requests merged in 2024-01, with the labels that each got.

#28 ✨ feat : 채팅 페이지 레이아웃 제작
  app/chatList/chatRoom/offerPrice/page.tsx
  app/chatList/chatRoom/page.tsx
  app/chatList/page.tsx
  components/chatList/chatItem/index.tsx
  components/chatList/index.tsx
  components/chatRoom/approveMessage/index.tsx
  components/chatRoom/offerBtn/index.tsx
  components/chatRoom/offerMessage/index.tsx
  components/chatRoom/productInfo/index.tsx
  components/chatRoom/receiveMessage/index.tsx
  components/chatRoom/selectedOfferMessage/index.tsx
  components/chatRoom/send/index.tsx
  components/chatRoom/sendMessage/index.tsx
  next.config.js
  package-lock.json
  package.json
  public/dotsVertical.svg
  public/productImage.png
  public/send.svg
Labels: feat

#34 ✨ feat : 헤더 요소 위치 고정, types 폴더 수정
  components/common/header/index.tsx
  types/common/header/types.ts
Labels: feat, chore

#33 ✨ feat : 구글/카카오 o-auth 세팅
  .eslintrc.js
  .gitignore
  api/socialAuth.ts
  app/login/_components/KakaoLoginButton.tsx
  app/login/_components/MyCustomButton.tsx
  app/login/email/page.tsx
  app/login/loading/page.tsx
  app/login/page.tsx
  components/common/provider/provider.tsx
  package-lock.json
  package.json
  public/Logo.png
  public/google_login_2x.png
  public/google_login_2xn.png
  public/kakao_login_medium_narrow.png
  public/kakao_login_medium_wide.png
  types/login/types.ts
Labels: feat

#35 ✨ feat : 구매 페이지 레이아웃 제작
  app/order/page.tsx
  components/common/header/index.tsx
  components/order/bookingHolderInfo/index.tsx
  components/order/checkInOut/index.tsx
  components/order/guestInfo/index.tsx
  components/order/modal/actionButton/index.tsx
  components/order/modal/index.tsx
  components/order/paymentButton/index.tsx
  components/order/paymentInfo/index.tsx
  components/order/paymentMethods/index.tsx
  components/order/productDetails/index.tsx
  components/order/termsAndConditions/index.tsx
  package-lock.json
  types/order/bookingHolderInfo/types.ts
  types/order/guestInfo/types.ts
  types/order/modal/actionButton/type.ts
  types/order/modal/type.ts
  types/order/paymentButton/type.ts
  types/order/productDetails/types.ts
  types/order/termsAndConditions/type.ts
Labels: feat

#40 feat : semantic tag 추가, 텍스트 변경 값 추가 pr
  __tests__/home.test.tsx
  app/mypage/dashboard/account/page.tsx
  app/mypage/dashboard/layout.tsx
  app/mypage/dashboard/profile/page.tsx
  app/mypage/page.tsx
  components/common/header/index.tsx
  components/common/layoutTemplate/RootTemplate/index.tsx
  components/mypage/account/accountBank/items/index.tsx
  components/mypage/account/accountBank/list/index.tsx
  components/mypage/account/accountContainer/index.tsx
  components/mypage/form/bankForm/form/index.tsx
  components/mypage/form/profileForm/form/index.test.tsx
  components/mypage/form/profileForm/form/index.tsx
  components/mypage/privacy/container/index.tsx
  components/mypage/privacy/items/index.tsx
  components/mypage/profile/profileButton/index.tsx
  constants/mypage.ts
  constants/zodSchema.ts
  hooks/useDebounceText.ts
  package-lock.json
  package.json
  public/svg/mypage-cancel.tsx
  tailwind.config.ts
  types/mypage/types.ts
  utils/mypage-utils.ts
Labels: style

#41 ✨ feat : 메인 페이지 레이아웃 구현
  app/home/page.tsx
  components/home/catch/catchContainer/index.tsx
  components/home/catch/catchItem/index.tsx
  components/home/catch/catchSwiper/index.tsx
  components/home/header/index.tsx
  components/home/review/reviewContainer/index.tsx
  components/home/review/reviewItem/index.tsx
  components/home/review/reviewSwiper/index.tsx
  components/home/saleButton/index.tsx
  components/home/searchBar/index.tsx
  package-lock.json
  package.json
  public/Ellipse-22.svg
  public/heart-action.svg
  public/marker-pin-01-filled.svg
  public/sample/Rectangle-70.png
  public/sample/accommodation.png
  public/search-md.svg
  public/svg/plus.svg
Labels: feat, style

#43 ✨ feat : 상세 페이지 레이아웃 제작 및 공동 컴포넌트 제작 (+ 기존 컴포넌트 개선)
  app/roominfo/page.tsx
  atoms/commons/heartButton.ts
  atoms/commons/toggleButton.ts
  atoms/roomInfo/navbarButton.ts
  components/catchItems/header/bottomHeader/index.tsx
  components/catchItems/header/topHeader/index.tsx
  components/common/catchComponent/index.tsx
  components/common/checkInDateComponent/index.tsx
  components/common/heartButton/index.tsx
  components/common/toggleButton/index.tsx
  components/roomInfo/body/index.tsx
  components/roomInfo/body/navbarSection/index.tsx
  components/roomInfo/body/navbarSection/navbarButton/index.tsx
  components/roomInfo/body/navbarSection/page/index.tsx
  components/roomInfo/body/roomImage/index.tsx
  components/roomInfo/body/roomInfo/index.tsx
  components/roomInfo/body/roomInfo/itemCheckIn/index.tsx
  components/roomInfo/body/roomInfo/itemDetails/index.tsx
  components/roomInfo/body/roomInfo/itemDetails/rateIcon/index.tsx
  components/roomInfo/body/roomInfo/sellerNote/index.tsx
  components/roomInfo/footer/index.tsx
  components/roomInfo/header/index.tsx
  components/roomInfo/header/leftButton/index.tsx
  components/roomInfo/header/leftButton/leftButtonIcon/index.tsx
  components/roomInfo/header/rightButton/index.tsx
  public/sample/map.png
  public/svg/xSymbol.svg
  public/svgComponent/downArrow.tsx
  public/svgComponent/emptyHeart.tsx
  public/svgComponent/fullHeart.tsx
  public/svgComponent/leftArrow.tsx
  public/svgComponent/xSymbol.tsx
  tailwind.config.ts
  types/common/catchItems/types.ts
  types/common/checkInComponent/types.ts
  types/roomInfo/types.ts
Labels: fix, feat, style, chore, refactor

#50 ✨ feat: 출금 계좌 등록 페이지 제작 pr
  app/mypage/dashboard/aaa/page.tsx
  app/mypage/dashboard/account/page.tsx
  app/mypage/dashboard/layout.tsx
  components/common/bottomSheets/index.test.tsx
  components/common/bottomSheets/index.tsx
  components/common/sheetsButtons/inputButton/index.tsx
  components/common/sheetsButtons/simpleButton/index.tsx
  components/mypage/form/bankForm/form/index.test.tsx
  components/mypage/form/bankForm/form/index.tsx
  constants/mypage.ts
  constants/zodSchema.ts
  package-lock.json
  package.json
  public/svg/sheet-close.tsx
  tailwind.config.ts
  utils/get-bank-name.ts
Labels: test, feat, style, chore

#54 ✨feat: 예치금 출금 페이지 제작 pr
  app/mypage/dashboard/aaa/page.tsx
  app/mypage/dashboard/account/page.tsx
  app/mypage/dashboard/profile/page.tsx
  app/mypage/dashboard/withdraw/page.tsx
  components/mypage/form/bankForm/index.test.tsx
  components/mypage/form/bankForm/index.tsx
  components/mypage/form/profileForm/index.test.tsx
  components/mypage/form/profileForm/index.tsx
  components/mypage/form/withdrawForm/index.test.tsx
  components/mypage/form/withdrawForm/index.tsx
  constants/zodSchema.ts
Labels: test, feat, style

#56 ✨ feat : 하단 nav 스타일 수정
  components/common/bottomNav/index.tsx
  public/svg/chatting.svg
  public/svg/face-smile.svg
  public/svg/home-line.svg
Labels: feat, style

#58 ✨ feat : 홈 화면 리뷰 전체 페이지 레이아웃 구현
  app/review/page.tsx
  components/home/review/reviewContainer/index.tsx
  components/review/reviewItem/index.tsx
Labels: feat, style

#65 ✨ feat: 판매내역 보기 페이지 제작 pr
  app/mypage/dashboard/account/page.tsx
  app/mypage/dashboard/layout.tsx
  app/mypage/dashboard/profile/page.tsx
  app/mypage/dashboard/sales/page.tsx
  app/mypage/dashboard/withdraw/history/page.tsx
  app/mypage/dashboard/withdraw/page.tsx
  app/mypage/page.tsx
  atoms/mypage/menuAtom.ts
  components/common/layoutTemplate/RootTemplate/index.tsx
  components/mypage/divider/index.tsx
  components/mypage/items/index.tsx
  components/mypage/items/reviewButtons/index.tsx
  components/mypage/items/topButtons/index.tsx
  components/mypage/menu/index.tsx
  constants/mypage.ts
  next.config.js
  public/svgComponent/threeDot.tsx
  types/mypage/types.ts
  utils/get-dot-date.ts
Labels: feat, style

#68 ✨ feat : 홈 화면 캐치특가 페이지 레이아웃 구현
  app/catchSale/page.tsx
  components/catchSale/catchItemContainer/index.tsx
  components/catchSale/secondHeader/index.tsx
  components/common/header/index.tsx
  components/home/catch/catchContainer/index.tsx
  components/home/catch/catchItem/index.tsx
  components/home/catch/catchSwiper/index.tsx
  components/home/review/reviewSwiper/index.tsx
  constants/catchItems.ts
  public/marker-pin.svg
  public/svgComponent/marker.tsx
  types/common/catchItems/types.ts
Labels: feat, style, refactor

#79 ✨ feat: 체크박스 공동 컴포넌트 제작
  atoms/commons/checkbox.ts
  components/common/checkBox/index.tsx
  public/svgComponent/checkbox/default.tsx
  public/svgComponent/checkbox/disabled.tsx
  public/svgComponent/checkbox/selected.tsx
  types/common/checkbox/types.ts
Labels: feat, style

#88 ✨ feat : 푸터 구현
  app/home/page.tsx
  components/catchSale/secondHeader/index.tsx
  components/common/bottomNav/index.tsx
  components/common/footer/index.tsx
  components/common/modal/index.tsx
  components/home/catch/catchItem/index.tsx
  components/home/review/reviewContainer/index.tsx
  public/Yanolja_CI.png
  public/svgComponent/marker/black.tsx
  public/svgComponent/marker/white.tsx
Labels: feat, style

#83 ✨feat: 마이페이지 디자인 반영 pr
  app/mypage/page.tsx
  components/mypage/account/accountButton/index.tsx
  components/mypage/account/accountContainer/index.tsx
  components/mypage/banner/bannerContainer/index.tsx
  components/mypage/banner/bannerFooter/index.tsx
  components/mypage/banner/bannerItem/index.tsx
  components/mypage/items/purchasingItems/index.tsx
  components/mypage/profile/profileButton/index.tsx
  components/mypage/profile/profileContainer/index.tsx
  constants/mypage.ts
  public/svgComponent/checkSheets.tsx
  public/svgComponent/money.tsx
  public/svgComponent/shoppingBag.tsx
  public/svgComponent/warning.tsx
  tailwind.config.ts
  types/mypage/types.ts
  utils/get-bank-name.ts
Labels: feat, style

#89 ✨feat : 채팅페이지 메시지 타입 추가
  app/chat/chatRoom/offerPrice/page.tsx
  app/chat/page.tsx
  components/chat/chatItem/index.tsx
  components/chat/chatRoom/Message/index.tsx
  components/chat/chatRoom/approveMessage/index.tsx
  components/chat/chatRoom/declineMessage/index.tsx
  components/chat/chatRoom/messageItem/index.tsx
  components/chat/chatRoom/messageList/index.tsx
  components/chat/chatRoom/offerMessage/index.tsx
  components/chat/chatRoom/productInfo/index.tsx
  components/chat/chatRoom/receiveMessage/index.tsx
  components/chat/chatRoom/selectedOfferMessage/index.tsx
  components/chat/chatRoom/sendMessage/index.tsx
  constants/chat.ts
  types/chat/chatRoom/types.ts
Labels: feat

#90 ✨feat : 바텀시트 컴포넌트 수정 및 상세검색 페이지 수정
  atoms/searchroom/checkbox.ts
  components/common/bottomSheets/index.tsx
  components/common/searchBoxButton/index.tsx
  components/common/selectBoxButton/index.tsx
  components/common/sheetsButtons/simpleButton/index.tsx
  components/searchroom/bodyComponent/footerComponent/index.tsx
  components/searchroom/bodyComponent/index.tsx
  components/searchroom/bodyComponent/searchComponent/index.tsx
  components/searchroom/headerComponent/index.tsx
  constants/serchpage.ts
  public/svgComponent/bigCalendar.tsx
  public/svgComponent/calendar.tsx
  public/svgComponent/house.tsx
  public/svgComponent/mapPin.tsx
  public/svgComponent/person.tsx
  types/common/searchBoxButton/types.ts
  types/common/selectBoxButton/types.ts
Labels: fix, feat, style, refactor

#96 🎨 style : 마감임박 페이지 디자인 변경
  components/catchItems/header/bottomHeader/index.tsx
  components/catchItems/header/index.tsx
  components/catchItems/header/middleHeader/index.tsx
  components/catchItems/header/topHeader/index.tsx
  components/catchItems/items/index.tsx
  public/svgComponent/downArrow.tsx
  public/svgComponent/mapPinSmFillIcon.tsx
Labels: style, refactor

#94 🎨 style: 슬라이드 버튼 스타일 수정 및 props 추가
  components/common/slideButton/index.tsx
  components/common/toggleButton/index.tsx
  types/common/slideButton/types.ts
Labels: fix, style, refactor

#100 🎨 style : 판매 페이지 디자인 수정
  app/sale/page.tsx
  atoms/sale/catch.ts
  components/common/checkInDateComponent/index.tsx
  components/common/slideButton/index.tsx
  components/sale/catch/catchContainer/index.tsx
  components/sale/checkboxContainer/index.tsx
  components/sale/line/index.tsx
  components/sale/price/index.tsx
  components/sale/saleEndContainer/index.tsx
  components/sale/saleInfoContainer/index.tsx
  components/sale/sellingPrice/sellingPriceContainer/index.tsx
  constants/CheckInOut.ts
  constants/zodSchema.ts
  public/svgComponent/questionMark.tsx
  tailwind.config.ts
  types/common/checkInComponent/types.ts
  types/common/product/types.ts
  types/common/slideButton/types.ts
Labels: style, refactor

#101 ✨feat: 마이페이지 계좌등록 페이지 디자인 #95 pr
  atoms/commons/outerBottomSheetsControl.ts
  atoms/mypage/divideAtom.ts
  components/common/bottomSheets/index.tsx
  components/common/sheetsButtons/inputButton/index.tsx
  components/common/sheetsButtons/simpleButton/index.tsx
  components/mypage/divideWrapper/index.tsx
  components/mypage/form/bankForm/index.test.tsx
  components/mypage/form/bankForm/index.tsx
  components/mypage/form/formError/index.tsx
  components/mypage/form/formInput/index.tsx
  components/mypage/form/profileForm/index.tsx
  components/mypage/privacy/privacyToggle/index.tsx
  constants/mypage.ts
  utils/get-bank-name.ts
Labels: feat, style, refactor

#102 🎨 style : 회원가입/로그인 페이지 레이아웃 변경
  app/login/loading/page.tsx
  app/login/page.tsx
  components/login/index.tsx
  components/loginSheets/index.tsx
  components/signup/index.tsx
  components/signup/next/index.tsx
  public/KakaoLoginButton.png
  public/LoginButton.png
  public/Logo.png
  types/login/types.ts
Labels: fix, feat, style

#104 🎨 style : 채팅페이지 디자인 반영
  app/chat/chatRoom/offerPrice/page.tsx
  app/chat/chatRoom/page.tsx
  app/chat/page.tsx
  atoms/chat/leaveButton.ts
  components/chat/chatItem/index.tsx
  components/chat/chatList/index.tsx
  components/chat/chatList/login/index.tsx
  components/chat/chatRoom/approveMessage/index.tsx
  components/chat/chatRoom/date/index.tsx
  components/chat/chatRoom/declineMessage/index.tsx
  components/chat/chatRoom/messageItem/index.tsx
  components/chat/chatRoom/offerBtn/index.tsx
  components/chat/chatRoom/offerMessage/index.tsx
  components/chat/chatRoom/productInfo/index.tsx
  components/chat/chatRoom/receiveMessage/index.tsx
  components/chat/chatRoom/send/index.tsx
  components/chat/chatRoom/sendMessage/index.tsx
  components/chat/chatRoom/userOut/index.tsx
  components/chat/common/defaultBtn/index.tsx
  components/common/bottomNav/index.tsx
  constants/chat.ts
  types/chat/chatItem/types.ts
Labels: feat, style

#106 ✨ feat: 검색 리스트 지도 모드제작
  app/layout.tsx
  app/search/layout.tsx
  app/search/map/page.tsx
  components/common/header/index.tsx
  components/search/filterBar/index.tsx
  components/search/filterButton/index.tsx
  components/search/map/catchSpecialComponentWrapper/index.tsx
  components/search/map/index.tsx
  components/search/map/toggleViewButtonWrapper/index.tsx
  components/search/toggleViewButton/index.tsx
  public/svg/Ellipse 25.svg
  public/svg/home-04.svg
  public/svg/home.svg
  public/svg/list.svg
  public/svg/map.svg
  types/common/header/types.ts
  types/common/types.ts
  types/search/FilterBar/types.ts
  types/search/FilterButton/types.ts
  types/search/map/type.ts
  types/search/toggleViewButton/types.ts
Labels: feat

#107 🐛 fix: 소셜로그인 삭제 및 로그인 페이지 수정
  api/socialAuth.ts
  app/login/email/page.tsx
  app/login/loading/page.tsx
  app/login/page.tsx
  components/login/index.tsx
  components/loginSheets/index.tsx
  components/signup/index.tsx
Labels: fix

#110 ✨feat : 판매 페이지 바텀 시트 구현
  app/home/page.tsx
  app/sale/page.tsx
  atoms/commons/outerBottomSheetsControl.ts
  atoms/sale/catch.ts
  atoms/sale/catchAtom.ts
  atoms/sale/priceAtom.ts
  components/common/bottomNav/index.tsx
  components/common/bottomSheets/index.tsx
  components/common/sheetsButtons/priceButton/index.tsx
  components/common/sheetsButtons/saleButton/index.tsx
  components/home/bottomsheetContent/saleItems/index.tsx
  components/home/saleButton/index.tsx
  components/sale/bottomSheetsContent/fromSeller/index.tsx
  components/sale/bottomSheetsContent/salePrice/index.tsx
  components/sale/catch/bottomSheetsContent/index.tsx
  components/sale/catch/catchContainer/index.tsx
  components/sale/catchBadge/index.tsx
  components/sale/checkboxContainer/index.tsx
  components/sale/discount/index.tsx
  components/sale/sellingPrice/bottomSheetsContent/index.tsx
  components/sale/sellingPrice/sellingPriceContainer/index.tsx
  constants/saleItems.ts
  constants/zodSchema.ts
  utils/get-slash-date.ts
Labels: feat, style, refactor

#113 🎨 style : 상품 상세페이지 디자인 수정 및 찜하기 공동 컴포넌트 수정
  app/roominfo/page.tsx
  app/search-detail/page.tsx
  atoms/commons/heartButton.ts
  atoms/roomInfo/headerTitle.ts
  components/common/catchComponent/index.tsx
  components/common/checkInDateComponent/index.tsx
  components/common/heartButton/index.tsx
  components/roomInfo/body/index.tsx
  components/roomInfo/body/navbarSection/index.tsx
  components/roomInfo/body/navbarSection/navbarButton/index.tsx
  components/roomInfo/body/navbarSection/page/accInfo/index.tsx
  components/roomInfo/body/navbarSection/page/accRegion/index.tsx
  components/roomInfo/body/navbarSection/page/index.tsx
  components/roomInfo/body/navbarSection/page/roomInfo/index.tsx
  components/roomInfo/body/roomImage/index.tsx
  components/roomInfo/body/roomInfo/index.tsx
  components/roomInfo/body/roomInfo/introduce/index.tsx
  components/roomInfo/body/roomInfo/itemCheckIn/index.tsx
  components/roomInfo/body/roomInfo/itemDetails/index.tsx
  components/roomInfo/body/roomInfo/itemDetails/rateIcon/index.tsx
  components/roomInfo/body/roomInfo/price/index.tsx
  components/roomInfo/body/roomInfo/sellerNote/index.tsx
  components/roomInfo/footer/index.tsx
  components/roomInfo/header/index.tsx
  components/roomInfo/header/leftButton/index.tsx
  components/roomInfo/header/leftButton/leftButtonIcon/index.tsx
  components/roomInfo/header/rightButton/index.tsx
  constants/catchItems.ts
  constants/introduce.ts
  constants/roomImage.ts
  public/sample/room4.png
  public/sample/room5.png
  public/svgComponent/emptyHeart.tsx
  public/svgComponent/fullHeart.tsx
  public/svgComponent/infoMark.tsx
  public/svgComponent/moreIcon.tsx
  public/svgComponent/roomInfo/navbarSection/bedIconSm.tsx
  public/svgComponent/roomInfo/navbarSection/personIconSm.tsx
  types/common/heartButton/types.ts
Labels: fix, feat, style, chore, refactor

#125 ✨ feat : 메인홈 달력선택 컴포넌트 제작 및 상세검색 페이지 디자인 수정
  app/catch-items/page.tsx
  atoms/checkInImnt/weekCalendar.ts
  atoms/searchroom/checkbox.ts
  components/catchItems/header/index.tsx
  components/catchItems/header/middleHeader/index.tsx
  components/catchItems/header/topHeader/index.tsx
  components/common/catchComponent/index.tsx
  components/common/weekCalendar/index.tsx
  components/home/catch/catchContainer/index.tsx
  components/home/checkIn/index.tsx
  components/home/header/index.tsx
  components/home/searchBar/index.tsx
  components/searchroom/bodyComponent/index.tsx
  components/searchroom/bodyComponent/searchComponent/confirmBtn/index.tsx
  components/searchroom/bodyComponent/searchComponent/index.tsx
  components/searchroom/bodyComponent/searchComponent/userCounter/index.tsx
  components/searchroom/headerComponent/index.tsx
  hooks/useBtnLoading.ts
  public/svgComponent/counter/minusBtn.tsx
  public/svgComponent/counter/plusBtn.tsx
Labels: feat, style, refactor

#122 ✨ feat: api 제작 및 admin 페이지 제작 #121 pr
  api/admin/api.ts
  api/admin/query.ts
  api/mypage/api.ts
  api/mypage/query.ts
  app/admin/page.tsx
  app/apitest/page.tsx
  app/mypage/dashboard/sales/page.tsx
  app/mypage/page.tsx
  app/stomp/sock/page.tsx
  components/mypage/divideWrapper/index.tsx
  components/mypage/divider/index.tsx
  components/mypage/form/formInput/index.tsx
  components/mypage/items/sellingItems/index.tsx
  lib/firebase.config.ts
  package-lock.json
  package.json
  pages/api/bypass/get.ts
  pages/api/testing/get.ts
  pages/api/v1/admin/history.ts
  pages/api/v1/admin/product.ts
  pages/api/v1/mypage/salesenroll.ts
  pages/api/v1/mypage/saleshistory.ts
  pages/api/v1/user/accesstoken.ts
  pages/api/v1/user/emailcheck.ts
  pages/api/v1/user/login.ts
  pages/api/v1/user/nicknamecheck.ts
  pages/api/v1/user/register.ts
  public/svgComponent/mediumCalendar.tsx
  types/mypage/data-types.ts
  utils/get-current-url.ts
  utils/get-dot-date.ts
Labels: feat

#127 ✨feat: 구매 페이지 디자인 반영
  app/order/page.tsx
  components/order/bookingHolderInfo/index.tsx
  components/order/guestInfo/index.tsx
  components/order/infoBox/index.tsx
  components/order/paymentButton/index.tsx
  components/order/paymentInfo/index.tsx
  components/order/paymentMethods/index.tsx
  components/order/productDetails/index.tsx
  components/order/termsAndConditions/index.tsx
  constants/order.ts
  constants/zodSchema.ts
  public/svg/info-circle.svg
  types/order/paymentInfo/types.ts
Labels: feat, style

#128 ✨ feat: 판매 내역 보기 페이지 디자인 #103 pr
  app/mypage/dashboard/review/page.tsx
  components/common/bottomSheets/index.tsx
  components/common/sheetsButtons/borderButton/index.tsx
  components/mypage/divideWrapper/index.tsx
  components/mypage/form/reviewForm/index.tsx
  components/mypage/items/reviewButtons/index.tsx
  components/mypage/items/sellingItems/index.tsx
  components/mypage/review/index.tsx
  pages/api/v1/mypage/saleshistory.ts
  types/mypage/data-types.ts
  utils/get-dot-date.ts
Labels: feat, style

#129 ✨ feat : 판매 페이지 추가 기능 및 모달 구현
  app/home/page.tsx
  app/sale/page.tsx
  atoms/sale/checkAtom.ts
  components/common/bottomSheets/index.tsx
  components/common/header/index.tsx
  components/common/modal/index.tsx
  components/common/sheetsButtons/validationButton/index.tsx
  components/common/slideButton/index.tsx
  components/mypage/items/sellingItems/index.tsx
  components/sale/catch/bottomSheetsContent/index.tsx
  components/sale/catch/catchContainer/index.tsx
  components/sale/checkboxContainer/index.tsx
  components/sale/sellingPrice/bottomSheetsContent/index.tsx
  components/sale/sellingPrice/sellingPriceContainer/index.tsx
  types/common/header/types.ts
  types/common/slideButton/types.ts
Labels: fix, feat, style

#132 ✨feat : 엑스 버튼없는 드롭다운 바텀시트 구현 및 디자인 일부 변경
  app/home/page.tsx
  atoms/catchSale/dropdownAtom.ts
  components/catchSale/secondHeader/index.tsx
  components/common/bottomSheets/index.tsx
  components/common/bottomSheetsWithOutCloseBtn/index.tsx
  components/common/sheetsButtons/dropdownButton/index.tsx
  components/home/bottomsheetContent/saleItems/index.tsx
  components/home/catch/catchItem/index.tsx
  components/home/catch/catchSwiper/index.tsx
  components/home/header/index.tsx
  components/home/review/reviewItem/index.tsx
  components/home/review/reviewSwiper/index.tsx
  components/home/saleButton/index.tsx
  constants/catchSale.ts
Labels: fix, feat, style, chore

#134 🐛 fix: hotfix conflict 해결 후 롤백된 사항 해결 #133 pr
  app/apitest/page.tsx
  app/chat/page.tsx
  app/stomp/sock/page.tsx
  components/mypage/items/sellingItems/index.tsx
  package.json
Labels: fix

#138 ♻ refactor : 상품 공동 컴포넌트 찜버튼 추가 및 페이지 이동 커스텀 훅 추가
  app/room-info/page.tsx
  components/catchItems/items/index.tsx
  components/common/catchComponent/index.tsx
  components/common/heartButton/index.tsx
  components/home/checkIn/index.tsx
  constants/catchItems.ts
  hooks/useBtnLoading.ts
  hooks/useProductInfoPage.ts
  types/common/catchItems/types.ts
  types/common/heartButton/types.ts
Labels: feat, refactor

#143 ✨ feat: 예치금 내역 디자인 #142 pr
  app/mypage/dashboard/profile/page.tsx
  app/mypage/dashboard/withdraw/history/page.tsx
  components/common/bottomSheets/index.tsx
  components/mypage/form/withdrawForm/index.tsx
  components/mypage/history/index.tsx
  constants/mypage.ts
  utils/get-dot-date.ts
  utils/mypage-utils.ts
Labels: feat, style

#135 ✨feat: 결제 완료 페이지 디자인 반영
  app/order/complete/page.tsx
  components/common/header/index.tsx
  components/complete/completeMessage/index.tsx
  components/complete/navButton/index.tsx
  components/complete/productDetails/index.tsx
  components/complete/reservationInfo/index.tsx
  public/sample/Yanolja_CI 1.png
  public/svg/check-circle.svg
  public/svg/x-close.svg
  types/common/header/types.ts
  types/complete/types.ts
  types/order/productDetails/types.ts
Labels: feat, style

#150 ✨feat: 결제 모달 디자인 반영
  components/order/modal/actionButton/index.tsx
  components/order/modal/bookingDetails/index.tsx
  components/order/modal/disclaimer/index.tsx
  components/order/modal/index.tsx
  components/order/paymentButton/index.tsx
Labels: feat, style

#151 ✨feat : ToastAlert 추가
  app/layout.tsx
  atoms/toastAlert/alert.ts
  components/common/toastAlert/index.tsx
  hooks/useToastAlert.ts
Labels: feat, style

#152 ✨ feat : 시간 picker 컴포넌트 구현
  atoms/commons/outerBottomSheetsControl.ts
  atoms/sale/timeAtom.ts
  components/common/bottomSheetsWithOutCloseBtn/index.tsx
  components/common/sheetsButtons/calendarButton/index.tsx
  components/home/bottomsheetContent/saleItems/index.tsx
  components/mypage/items/sellingItems/index.tsx
  components/sale/bottomSheetsContent/fromSeller/index.tsx
  components/sale/saleEndContainer/index.tsx
  components/sale/setTime/index.tsx
  public/svgComponent/downArrow.tsx
  public/svgComponent/upArrow.tsx
Labels: feat, style

#147 ✨ feat: 로그인/회원가입 레이아웃 수정 및 api 테스트
  api/mypage/api.ts
  api/mypage/query.ts
  api/mypage/testApi.ts
  api/user/api.ts
  app/login/page.tsx
  app/signup/next/page.tsx
  app/signup/page.tsx
  atoms/signup/signup.ts
  components/login/index.tsx
  components/signup/index.tsx
  components/signup/next/index.tsx
  package-lock.json
  package.json
  public/svgComponent/nextArrow.tsx
Labels: feat, style

#153 ✨ feat: 찜 목록 페이지 디자인 #146 pr
  amplify.yml
  api/admin/api.ts
  app/admin/page.tsx
  app/mypage/dashboard/layout.tsx
  app/mypage/dashboard/wishlist/page.tsx
  components/mypage/divider/wishListDivider/index.tsx
  components/mypage/header/index.tsx
  components/mypage/history/index.tsx
  components/mypage/items/sellingItems/index.tsx
  constants/mypage.ts
Labels: feat, style, chore

#156 ✨feat: 결제 완료 후 상세보기 페이지 제작, 타입 오류 관련 수정
  app/order/complete/detail/page.tsx
  app/order/complete/page.tsx
  app/order/page.tsx
  components/complete/productDetails/index.tsx
  components/complete/reservationInfo/index.tsx
  components/detail/ReservationDetail/index.tsx
  components/detail/ReservationSummary/index.tsx
  components/order/guestInfo/index.tsx
  components/order/infoBox/index.tsx
  components/order/productDetails/index.tsx
  constants/order.ts
  types/detail/types.ts
  types/order/productDetails/types.ts
Labels: feat, style

#161 ✨feat: 이메일 회원가입/로그인 api 연동 및 미들웨어 설정
  api/mypage/api.ts
  api/user/api.ts
  api/user/apiClient.ts
  components/login/index.tsx
  components/signup/index.tsx
  components/signup/next/index.tsx
  middleware.ts
Labels: feat, style

#160 🐛 fix : 모달 오버사이즈 관련해서 유동적인 h-value 조정 pr
  components/mypage/divideWrapper/index.tsx
  components/mypage/form/bankForm/index.tsx
Labels: fix, style

#166 🐛 fix : 메인, 판매 페이지 수정
  app/home/page.tsx
  app/sale/page.tsx
  components/home/bottomsheetContent/saleItems/index.tsx
  components/home/catch/catchItem/index.tsx
  components/home/catch/catchSwiper/index.tsx
  components/home/review/reviewItem/index.tsx
  components/review/reviewItem/index.tsx
  components/sale/checkboxContainer/index.tsx
  components/sale/saleInfoContainer/index.tsx
  types/common/catchItems/types.ts
Labels: fix, feat, style, refactor

#170 ✨feat: 회원가입/로그인 스타일 추가 및 기타 작업
  api/mypage/api.ts
  api/user/api.ts
  api/user/apiClient.ts
  app/mypage/page.tsx
  components/login/index.tsx
  components/mypage/logout/index.tsx
  components/signup/index.tsx
  components/signup/next/index.tsx
  middleware.ts
Labels: feat, style

#172 ✨ feat : 상품 상세 바텀시트 구현
  atoms/commons/outerBottomSheetsControl.ts
  components/common/bottomSheetsWithOutCloseBtn/index.tsx
  components/common/modal/index.tsx
  components/common/sheetsButtons/moreButton/index.tsx
  components/roomInfo/header/index.tsx
Labels: feat, style

#175 ✨ feat : 검색 결과 지도 모드 수정, 공통 헤더 수정, 검색 결과 페이지 레이아웃 재설정
  app/order/complete/detail/page.tsx
  app/order/page.tsx
  app/search-result/(noSortBtn)/layout.tsx
  app/search-result/(noSortBtn)/map/page.tsx
  app/search-result/(sortBtn)/layout.tsx
  app/search-result/(sortBtn)/list/page.tsx
  app/search-result/(sortBtn)/no-results/page.tsx
  components/catchSale/catchItemContainer/index.tsx
  components/common/bottomSheetsWithOutCloseBtn/index.tsx
  components/common/header/index.tsx
  components/search-result/filterBar/index.tsx
  components/search-result/list/productListControls/index.tsx
  components/search-result/list/sortOptionsButton/index.tsx
  components/search-result/map/catchSpecialComponentWrapper/index.tsx
  components/search-result/map/index.tsx
Labels: feat, style

#176 ✨feat : 판매 페이지 디자인 피드백 수정
  app/layout.tsx
  components/common/bottomSheetsWithOutCloseBtn/index.tsx
  components/common/header/index.tsx
  components/common/sheetsButtons/calendarButton/index.tsx
  components/common/sheetsButtons/inputButton/index.tsx
  components/common/sheetsButtons/priceButton/index.tsx
  components/sale/bottomSheetsContent/fromSeller/index.tsx
  components/sale/catch/bottomSheetsContent/index.tsx
  components/sale/catch/catchContainer/index.tsx
  components/sale/checkboxContainer/index.tsx
  components/sale/saleEndContainer/index.tsx
  components/sale/saleInfoContainer/index.tsx
  components/sale/sellingPrice/bottomSheetsContent/index.tsx
  components/sale/sellingPrice/sellingPriceContainer/index.tsx
  components/sale/setTime/index.tsx
  hooks/useLongPress.ts
  package-lock.json
  public/svgComponent/clock.tsx
Labels: fix, feat, style

#178 ✨ feat: 달력 바텀시트 디자인 적용 및 기능구현
  atoms/calendar/calendarAtoms.ts
  atoms/search-detail/checkbox.ts
  atoms/searchroom/checkbox.ts
  components/common/calendar/custom-styles.css
  components/common/calendar/index.tsx
  components/searchroom/bodyComponent/searchComponent/index.tsx
  components/searchroom/bodyComponent/searchComponent/userCounter/index.tsx
  constants/search-detail.ts
  package-lock.json
  package.json
  public/svgComponent/calendar/midline.tsx
  types/common/calendar/type.ts
Labels: feat, style

#179 ✨feat : 채팅 API 적용
  api/chat/api.ts
  app/chat/chatRoom/offerPrice/page.tsx
  app/chat/chatRoom/page.tsx
  app/chat/page.tsx
  app/stomp/sock/page.tsx
  components/chat/chatRoom/WebSocketConnection/WebSocketConnection.tsx
  components/chat/chatRoom/messageItem/index.tsx
  components/chat/chatRoom/messageList/index.tsx
  components/chat/chatRoom/receiveMessage/index.tsx
  components/chat/chatRoom/send/index.tsx
  components/chat/chatRoom/sendMessage/index.tsx
  package.json
  public/svgComponent/sendIcon.tsx
  types/chat/chatRoom/types.ts
  utils/formatTime.ts
Labels: feat

#183 🔥 remove : 사용하지 않는 코드 삭제
  api/chat/api.ts
  app/chat/chatRoom/page.tsx
  app/chat/page.tsx
  app/stomp/sock/page.tsx
Labels: refactor

#185 🧪 test : 판매 페이지 테스트 코드 작성
  components/common/modal/index.tsx
  components/common/sheetsButtons/inputButton/index.tsx
  components/common/sheetsButtons/priceButton/index.tsx
  components/common/sheetsButtons/validationButton/index.tsx
  components/common/slideButton/index.tsx
  components/home/bottomsheetContent/saleItems/index.tsx
  components/mypage/form/profileForm/index.test.tsx
  components/sale/catch/catchContainer/index.test.tsx
  components/sale/catch/catchContainer/index.tsx
  components/sale/checkboxContainer/index.test.tsx
  components/sale/checkboxContainer/index.tsx
  components/sale/sellingPrice/sellingPriceContainer/index.test.tsx
  components/sale/sellingPrice/sellingPriceContainer/index.tsx
  public/svgComponent/checkbox/selected.tsx
Labels: test

#195 ✨ feat : 검색 바텀시트 버튼 props 추가 및 디바운스 처리
  .github/ISSUE_TEMPLATE/issue_template.yml
  app/deadline-items/page.tsx
  atoms/calendar/calendarAtoms.ts
  atoms/search-detail/checkbox.ts
  atoms/search-detail/searchStates.ts
  components/catchItems/header/bottomHeader/index.tsx
  components/common/bottomSheets/index.tsx
  components/common/calendar/index.tsx
  components/common/searchBtmSheets/calendar/index.tsx
  components/common/searchBtmSheets/customer/index.tsx
  components/common/searchBtmSheets/region/index.tsx
  components/common/searchBtmSheets/room/index.tsx
  components/common/sheetsButtons/dropdownButton/index.tsx
  components/home/checkIn/index.tsx
  components/searchroom/bodyComponent/searchComponent/index.tsx
  components/searchroom/bodyComponent/searchComponent/userCounter/index.tsx
  components/searchroom/headerComponent/index.tsx
  hooks/useResetSearchAtoms.ts
  package.json
Labels: feat, refactor

#193 🧪 test : playwright 회원가입 TC 기준 테스트 진행 #192 pr
  .github/workflows/playwright.yml
  .gitignore
  api/chat/api.ts
  api/chat/apiChatClient.ts
  api/chat/query.ts
  app/chat/chatRoom/page.tsx
  app/chat/layout.tsx
  app/chat/page.tsx
  app/loading.tsx
  app/stomp/sock/page.tsx
  app/talk/FindRoomInfo.tsx
  app/talk/LoginButton.tsx
  app/talk/[room]/Room.tsx
  app/talk/[room]/page.tsx
  app/talk/chattingRoom.tsx
  app/talk/makeChattingButton.tsx
  app/talk/page.tsx
  app/talks/page.tsx
  atoms/chat/chatContentAtom.ts
  components/chat/chatItem/index.tsx
  components/chat/chatList/control/index.tsx
  components/chat/chatList/index.tsx
  components/chat/chatList/modalControl/index.tsx
  components/chat/chatList/wrapper/index.tsx
  components/loginSheets/index.tsx
  components/mypage/form/formError/index.test.tsx
  components/mypage/form/formError/index.tsx
  components/mypage/form/formInput/index.test.tsx
  components/mypage/form/reviewForm/index.test.tsx
  components/mypage/form/reviewForm/index.tsx
  e2e/example.spec.js
  middleware.ts
  next.config.js
  package-lock.json
  package.json
  playwright.config.js
  playwright.config.ts
  public/svgComponent/wonIcon.tsx
  tests/signUp.spec.ts
  tsconfig.json
  types/chat/chatRoom/types.ts
Labels: test

#200 ♻️ refactor : 정책 및 스타일 변경으로 인한 검색 컴포넌트 변경사항 반영
  app/search-detail/loading.tsx
  components/common/calendar/custom-styles.css
  components/common/calendar/index.tsx
  components/common/searchBtmSheets/calendar/index.tsx
  components/searchroom/bodyComponent/searchComponent/userCounter/index.tsx
  constants/search-detail.ts
  public/svgComponent/downArrow.tsx
Labels: refactor

#198 ✨feat: 마이페이지 프로필/예치금 api연결 및 회원가입/마이페이지 수정사항 반영
  api/mypage/api.ts
  api/mypage/query.ts
  api/user/api.ts
  api/user/apiClient.ts
  app/mypage/dashboard/profile/page.tsx
  app/mypage/dashboard/withdraw/history/page.tsx
  app/mypage/dashboard/withdraw/page.tsx
  app/mypage/page.tsx
  app/signup/next/page.tsx
  app/signup/page.tsx
  components/login/index.tsx
  components/loginSheets/index.tsx
  components/mypage/account/accountContainer/index.tsx
  components/mypage/account/history/index.tsx
  components/mypage/account/withdraw/index.tsx
  components/mypage/divider/index.tsx
  components/mypage/form/bankForm/index.tsx
  components/mypage/form/profileForm/index.tsx
  components/mypage/form/withdrawForm/index.tsx
  components/mypage/history/index.tsx
  components/mypage/privacy/items/index.tsx
  components/mypage/profile/profileContainer/index.tsx
  components/signup/index.tsx
  components/signup/next/index.tsx
  constants/mypage.ts
  constants/zodSchema.ts
  middleware.ts
  package-lock.json
  package.json
  public/svgComponent/verifiedIcon.tsx
  utils/get-dot-date.ts
Labels: fix, feat, style

#208 🐛 hotfix: 배포 문제 해결 #207
  api/chat/api.ts
  api/chat/query.ts
  api/chat/serverApi.ts
  app/chat/[room]/page.tsx
  app/chat/chatRoom/page.tsx
  app/chat/offerPrice/page.tsx
  app/chat/page.tsx
  app/search-result/(noSortBtn)/layout.tsx
  app/search-result/(sortBtn)/layout.tsx
  app/stomp/sock/page.tsx
  app/talk/LoginButton.tsx
  app/talk/[room]/Room.tsx
  app/talk/makeChattingButton.tsx
  atoms/chat/chatContentAtom.ts
  components/chat/chatItem/index.tsx
  components/chat/chatList/control/index.tsx
  components/chat/chatList/viewer/index.tsx
  components/chat/chatRoom/control/index.tsx
  components/chat/chatRoom/sender/index.tsx
  components/chat/chatRoom/viewer/index.tsx
  components/chat/chatRoom/wrapper/index.tsx
  components/common/provider/provider.tsx
  components/mypage/divider/index.tsx
  components/mypage/form/withdrawForm/index.tsx
  hooks/useChatConnection.ts
  next.config.js
  public/svgComponent/sendIcon.tsx
  public/svgComponent/xSymbol.tsx
  types/chat/chatRoom/types.ts
Labels: fix

#204 ✨feat : 검색 결과 페이지에 검색 바텀시트 버튼 적용
  app/search-result/(noSortBtn)/layout.tsx
  app/search-result/(sortBtn)/layout.tsx
  app/search-result/(sortBtn)/list/page.tsx
  atoms/order/paymentMethodAtom.ts
  atoms/order/termsAgreementAtom.ts
  components/common/catchComponent/index.tsx
  components/common/header/index.tsx
  components/order/guestInfo/index.tsx
  components/order/modal/index.tsx
  components/order/paymentButton/index.tsx
  components/order/paymentInfo/index.tsx
  components/order/paymentMethods/index.tsx
  components/order/termsAndConditions/index.tsx
  components/search-result/filterBar/index.tsx
  components/search-result/filterButton/index.tsx
  components/search-result/list/productListControls/index.tsx
  components/search-result/map/index.tsx
  types/order/modal/type.ts
  types/search-result/FilterButton/types.ts
Labels: feat, style

#205 ✨feat : 판매 페이지 달력, 시간 설정 모달 구현
  app/sale/page.tsx
  atoms/search-detail/searchStates.ts
  components/catchSale/catchItemContainer/index.tsx
  components/catchSale/secondHeader/index.tsx
  components/common/calendar/index.tsx
  components/common/header/index.tsx
  components/sale/catch/catchContainer/index.tsx
  components/sale/saleEndContainer/index.tsx
  components/sale/setTime/index.tsx
  types/common/calendar/type.ts
  utils/get-date-with-day.ts
Labels: feat, style

#206 ✨ feat : 구매 페이지 수정 사항 반영, 미입력, 미체크시 로직 수정
  app/order/complete/detail/page.tsx
  app/order/page.tsx
  atoms/order/formSubmissionAtom.ts
  atoms/order/guestInfoAtom.ts
  components/common/header/index.tsx
  components/complete/completeMessage/index.tsx
  components/order/guestInfo/index.tsx
  components/order/modal/index.tsx
  components/order/paymentButton/index.tsx
  components/order/paymentMethods/index.tsx
  constants/zodSchema.ts
  types/common/header/types.ts
  types/order/guestInfo/types.ts
  types/order/paymentButton/type.ts
Labels: feat, style

#211 🐛 fix: prettier에러 해결
  components/order/guestInfo/index.tsx
  components/order/paymentButton/index.tsx
  components/order/paymentMethods/index.tsx
Labels: fix

#215 ✨ feat : 판매 API 연결
  api/home/api.ts
  api/home/query.ts
  api/sale/api.ts
  api/sale/query.ts
  api/user/apiClient.ts
  app/home/page.tsx
  app/sale/page.tsx
  atoms/sale/catchAtom.ts
  atoms/sale/headerAtom.ts
  atoms/sale/priceAtom.ts
  atoms/sale/timeAtom.ts
  components/common/bottomSheets/index.tsx
  components/common/calendar/custom-styles.css
  components/common/header/index.tsx
  components/common/sheetsButtons/inputButton/index.tsx
  components/common/sheetsButtons/saleButton/index.tsx
  components/common/sheetsButtons/validationButton/index.tsx
  components/home/bottomsheetContent/saleItems/index.tsx
  components/home/content/index.tsx
  components/mypage/form/profileForm/index.tsx
  components/sale/bottomSheetsContent/fromSeller/index.tsx
  components/sale/catch/catchContainer/index.tsx
  components/sale/saleEndContainer/index.tsx
  components/sale/saleInfoContainer/index.tsx
  components/sale/sellingPrice/sellingPriceContainer/index.tsx
  components/sale/setTime/index.tsx
  public/svgComponent/downArrow.tsx
  types/common/product/types.ts
  types/home/types.ts
  types/sale/type.ts
  utils/get-dot-date.ts
  utils/get-slash-date.ts
Labels: fix, feat, style

#216 ✨ feat : not-found, loading 페이지 제작
  app/chat/[room]/offerPrice/page.tsx
  app/chat/layout.tsx
  app/loading.tsx
  app/not-found.tsx
  app/stomp/sock/page.tsx
  atoms/chat/chatContentAtom.ts
  components/chat/chatRoom/approveMessage/index.tsx
  components/chat/chatRoom/declineMessage/index.tsx
  components/chat/chatRoom/messageItem/index.tsx
  components/chat/chatRoom/offerMessage/index.tsx
  components/chat/chatRoom/productInfo/index.tsx
  components/chat/chatRoom/receiveMessage/index.tsx
  components/chat/chatRoom/sendMessage/index.tsx
  components/chat/chatRoom/sender/index.tsx
  components/chat/chatRoom/viewer/index.tsx
  components/chat/common/defaultBtn/index.tsx
  package-lock.json
  package.json
  tailwind.config.ts
  types/chat/chatRoom/types.ts
  utils/formatCurrency.ts
Labels: feat

#221 ✨ 상품 상세페이지 API 연결 및 스켈레톤 UI 구현
  api/deadline-items/api.ts
  api/room-info/api.ts
  api/room-info/query.ts
  app/room-info/[id]/page.tsx
  app/search-detail/loading.tsx
  atoms/roomInfo/navbarButton.ts
  components/catchItems/header/bottomHeader/index.tsx
  components/catchItems/items/index.tsx
  components/common/calendar/custom-styles.css
  components/common/searchBtmSheets/calendar/index.tsx
  components/common/searchBtmSheets/customer/index.tsx
  components/common/searchBtmSheets/region/index.tsx
  components/common/searchBtmSheets/room/index.tsx
  components/common/sheetsButtons/dropdownButton/index.tsx
  components/home/checkIn/index.tsx
  components/roomInfo/body/navbarSection/navbarButton/index.tsx
  components/roomInfo/body/navbarSection/page/accRegion/index.tsx
  components/roomInfo/body/navbarSection/page/roomInfo/index.tsx
  components/roomInfo/body/roomImage/index.tsx
  components/roomInfo/body/roomInfo/introduce/index.tsx
  components/roomInfo/body/roomInfo/itemCheckIn/index.tsx
  components/roomInfo/body/roomInfo/itemDetails/index.tsx
  components/roomInfo/body/roomInfo/price/index.tsx
  components/roomInfo/body/roomInfo/sellerNote/index.tsx
  components/roomInfo/footer/index.tsx
  components/roomInfo/header/index.tsx
  components/roomInfo/header/rightButton/index.tsx
  hooks/useProductInfoPage.ts
  public/svgComponent/downArrow.tsx
  types/common/product/types.ts
  types/room-info/types.ts
Labels: fix, feat, style

#222 ✨feat : 홈 캐치특가, 리뷰 API 연결
  api/home/api.ts
  api/home/query.ts
  api/sale/query.ts
  app/review/page.tsx
  components/catchSale/catchItemContainer/index.tsx
  components/catchSale/secondHeader/index.tsx
  components/common/header/index.tsx
  components/home/catch/catchContainer/index.tsx
  components/home/catch/catchItem/index.tsx
  components/home/catch/catchSwiper/index.tsx
  components/home/header/index.tsx
  components/home/review/reviewItem/index.tsx
  components/home/review/reviewSwiper/index.tsx
  components/home/searchBar/index.tsx
  components/review/reviewContainer/index.tsx
  components/review/reviewItem/index.tsx
  components/sale/bottomSheetsContent/fromSeller/index.tsx
  public/svgComponent/logo.tsx
  tailwind.config.ts
  types/common/catchItems/types.ts
  types/home/types.ts
  utils/get-date-with-dash.ts
Labels: fix, feat, style

#225 ✨ feat : 마이페이지 판매내역/구매내역/찜내역 api 연결
  api/mypage/api.ts
  api/mypage/query.ts
  api/user/apiClient.ts
  app/login/page.tsx
  app/mypage/dashboard/purchase/page.tsx
  app/mypage/dashboard/wishlist/page.tsx
  components/common/catchComponent/index.tsx
  components/login/index.tsx
  components/mypage/account/wishlist/index.tsx
  components/mypage/dashboard/index.tsx
  components/mypage/divider/index.tsx
  components/mypage/history/index.tsx
  components/mypage/items/deleteButtons/index.tsx
  components/mypage/items/purchasingItems/index.tsx
  components/mypage/items/reviewButtons/index.tsx
  components/mypage/items/reviewContent/index.tsx
  components/mypage/items/sellingItems/index.tsx
  components/mypage/items/wishListHeartControl/index.tsx
  components/signup/next/index.tsx
  constants/catchItems.ts
  public/Logo.png
  types/mypage/data-types.ts
  utils/get-dot-date.ts
Labels: feat

#226 ✨feat : 홈 화면 스켈레톤 UI 추가
  api/sale/api.ts
  api/sale/query.ts
  atoms/sale/productAtom.ts
  components/common/modal/index.tsx
  components/home/catch/catchItem/index.tsx
  components/home/catch/catchSkeletonUI/index.tsx
  components/home/catch/catchSwiper/index.tsx
  components/home/review/ReviewSkeletonUI/index.tsx
  components/home/review/reviewSwiper/index.tsx
  components/review/reviewContainer/index.tsx
  components/review/reviewSkeletonUI/index.tsx
  components/roomInfo/header/index.tsx
  components/sale/bottomSheetsContent/fromSeller/index.tsx
  components/sale/saleInfoContainer/index.tsx
Labels: feat, style

#229 ✨feat : 판매 API 연결
  api/sale/api.ts
  api/sale/query.ts
  atoms/sale/pageAtom.ts
  atoms/sale/productAtom.ts
  components/common/header/index.tsx
  components/roomInfo/header/leftButton/index.tsx
  components/sale/bottomSheetsContent/fromSeller/index.tsx
  components/sale/catch/catchContainer/index.tsx
  components/sale/saleEndContainer/index.tsx
  components/sale/saleInfoContainer/index.tsx
  types/sale/type.ts
Labels: fix, feat

#231 ♻ refactor : 상품 상세페이지 숙소 정보 추가 및 공동 컴포넌트 날짜 props 세분화
  components/catchItems/items/index.tsx
  components/common/calendar/index.tsx
  components/common/catchComponent/index.tsx
  components/common/checkInDateComponent/index.tsx
  components/common/searchBoxButton/index.tsx
  components/common/searchBtmSheets/calendar/index.tsx
  components/common/searchBtmSheets/customer/index.tsx
  components/common/searchBtmSheets/region/index.tsx
  components/common/searchBtmSheets/room/index.tsx
  components/home/checkIn/index.tsx
  components/roomInfo/body/navbarSection/navbarButton/index.tsx
  components/roomInfo/body/navbarSection/page/accInfo/index.tsx
  components/roomInfo/body/navbarSection/page/accRegion/index.tsx
  components/roomInfo/body/navbarSection/page/roomInfo/index.tsx
  components/roomInfo/body/roomInfo/itemCheckIn/index.tsx
  components/roomInfo/body/roomInfo/price/index.tsx
  components/roomInfo/footer/index.tsx
  components/searchroom/bodyComponent/searchComponent/userCounter/index.tsx
  public/svgComponent/roomInfo/navbarSection/pinkCheckIcon.tsx
Labels: style, refactor

#235 ✨feat: 마이페이지 리뷰, 상세조회 api연결
  api/mypage/api.ts
  api/mypage/query.ts
  api/user/apiClient.ts
  app/mypage/dashboard/review/page.tsx
  app/order/complete/detail/page.tsx
  components/detail/ReservationDetail/index.tsx
  components/detail/ReservationSummary/index.tsx
  components/mypage/form/reviewForm/index.tsx
  components/mypage/header/index.tsx
  components/mypage/history/index.tsx
  components/mypage/items/purchasingItems/index.tsx
  components/mypage/items/reviewButtons/index.tsx
  components/mypage/items/reviewContent/index.tsx
  components/mypage/items/sellingItems/index.tsx
  components/mypage/profile/profileContainer/index.tsx
  components/mypage/review/index.tsx
  components/order/complete/detail/index.tsx
  components/roomInfo/footer/index.tsx
  components/signup/index.tsx
  components/signup/next/index.tsx
  constants/zodSchema.ts
  types/mypage/data-types.ts
Labels: fix, feat

#234 ✨ feat : 무한 스크롤 구현 및 몇가지 오류 수정
  api/home/api.ts
  api/home/query.ts
  app/catchSale/page.tsx
  app/review/page.tsx
  atoms/catchSale/dropdownAtom.ts
  atoms/catchSale/totalSizeAtom.ts
  components/catchSale/InfiniteScrollWrapper/index.tsx
  components/catchSale/catchItemContainer/index.tsx
  components/catchSale/secondHeader/index.tsx
  components/common/sheetsButtons/inputButton/index.tsx
  components/home/catch/catchItem/index.tsx
  components/review/InfiniteScrollWrapper/index.tsx
  components/review/reviewContainer/index.tsx
  components/review/reviewSkeletonUI/index.tsx
  components/sale/bottomSheetsContent/fromSeller/index.tsx
  components/sale/catch/catchContainer/index.tsx
  components/sale/saleEndContainer/index.tsx
  components/sale/saleInfoContainer/index.tsx
  components/sale/sellingPrice/sellingPriceContainer/index.tsx
  next.config.js
  types/sale/type.ts
Labels: fix, feat

#237 ✨ feat: 채팅방 완성 #236 pr
  api/chat/api.ts
  api/chat/apiChatClient.ts
  api/chat/query.ts
  atoms/chat/chatContentAtom.ts
  atoms/chat/leaveButton.ts
  components/chat/chatItem/index.tsx
  components/chat/chatRoom/approveMessage/index.tsx
  components/chat/chatRoom/control/index.tsx
  components/chat/chatRoom/infiniteWrapper/index.tsx
  components/chat/chatRoom/messageItem/index.tsx
  components/chat/chatRoom/offerMessage/index.tsx
  components/chat/chatRoom/offerModal/index.tsx
  components/chat/chatRoom/productInfo/index.tsx
  components/chat/chatRoom/sendMessage/index.tsx
  components/chat/chatRoom/sender/index.tsx
  components/chat/chatRoom/userOut/index.tsx
  components/chat/chatRoom/viewer/index.tsx
  components/chat/header/index.tsx
  components/chat/skeleton/index.tsx
  hooks/useChatConnection.ts
  hooks/useRoomConnection.ts
  package-lock.json
  package.json
  public/svgComponent/sendIcon.tsx
  tailwind.config.ts
  types/chat/chatRoom/types.ts
Labels: fix, feat, refactor

#242 ✨ feat : 체크인 마감임박 페이지 무한 스크롤 기능 구현 및 refactor 진행
  api/deadline-items/api.ts
  api/deadline-items/query.ts
  atoms/catchSale/dropdownAtom.ts
  components/catchItems/header/bottomHeader/index.tsx
  components/catchItems/items/index.tsx
  components/common/catchComponent/index.tsx
  components/home/checkIn/index.tsx
  components/roomInfo/footer/index.tsx
Labels: fix, feat, refactor

#245 ✨ feat : 에러 수정 및 로그인 모달 추가
  api/chat/api.ts
  components/roomInfo/footer/index.tsx
Labels: feat

#246 🐛 fix : 오류 수정
  atoms/sale/pageAtom.ts
  components/catchSale/InfiniteScrollWrapper/index.tsx
  components/common/header/index.tsx
  components/common/modal/index.tsx
  components/common/sheetsButtons/moreButton/index.tsx
  components/common/sheetsButtons/priceButton/index.tsx
  components/home/catch/catchSkeletonUI/index.tsx
  components/home/review/ReviewSkeletonUI/index.tsx
  components/home/review/reviewItem/index.tsx
  components/review/InfiniteScrollWrapper/index.tsx
  components/review/reviewItem/index.tsx
  components/review/reviewSkeletonUI/index.tsx
  components/roomInfo/header/leftButton/index.tsx
  components/sale/bottomSheetsContent/fromSeller/index.tsx
  components/sale/catch/catchContainer/index.tsx
  components/sale/saleEndContainer/index.tsx
  components/sale/saleInfoContainer/index.tsx
  types/sale/type.ts
Labels: fix, style

#249 ✨ feat : 회원가입/마이페이지 수정
  components/login/index.tsx
  components/mypage/form/profileForm/index.tsx
  components/mypage/form/reviewForm/index.tsx
  components/mypage/form/withdrawForm/index.test.tsx
  components/mypage/items/deleteButtons/index.tsx
  components/mypage/items/purchasingItems/index.tsx
  components/mypage/items/reviewContent/index.tsx
  components/mypage/items/sellingItems/index.tsx
  components/mypage/items/wishListHeartControl/index.tsx
  components/signup/index.tsx
  components/signup/next/index.tsx
  constants/zodSchema.ts
  package-lock.json
  package.json
Labels: fix, feat

#248 ✨ feat: 검색 페이지 수정
  app/search-result/(noSortBtn)/layout.tsx
  app/search-result/(noSortBtn)/map/page.tsx
  app/search-result/(sortBtn)/layout.tsx
  app/search-result/(sortBtn)/list/page.tsx
  components/common/header/index.tsx
  components/search-result/filterBar/index.tsx
  components/search-result/list/accommodationList/index.tsx
  components/search-result/list/productListControls/index.tsx
Labels: feat, style

#251 ✨ feat : 마감임박 페이지 & 컴포넌트 스켈레톤 UI 완성
  app/home/page.tsx
  components/catchItems/header/middleHeader/index.tsx
  components/catchItems/items/index.tsx
  components/common/catchComponent/index.tsx
  components/common/toastAlert/index.tsx
  components/home/deadLineItems/deadLineSkeletonUI/idex.tsx
  components/home/deadLineItems/index.tsx
  components/roomInfo/body/navbarSection/page/roomInfo/index.tsx
  next.config.js
Labels: feat, style, refactor

#255 🐛 fix : userId 변수명 변경 pr
  components/chat/chatRoom/messageItem/index.tsx
  hooks/useChatConnection.ts
  hooks/useRoomConnection.ts
Labels: fix

#258 ✨ feat : 약관 연결
  components/common/footer/index.tsx
  components/sale/checkboxContainer/index.tsx
Labels: feat, chore

#260 ♻️ refactor : 채팅방 사용하지 않는 콘솔 삭제 및 UI 변경 #259 pr
  api/chat/api.ts
  api/chat/apiChatClient.ts
  api/chat/query.ts
  app/mypage/dashboard/loading.tsx
  app/stomp/sock/page.tsx
  app/talks/page.tsx
  components/chat/chatItem/index.tsx
  components/chat/chatList/modalControl/index.tsx
  components/chat/chatList/wrapper/index.tsx
  components/chat/chatRoom/approveMessage/index.tsx
  components/chat/chatRoom/declineMessage/index.tsx
  components/chat/chatRoom/messageItem/index.tsx
  components/chat/chatRoom/offerMessage/index.tsx
  components/chat/chatRoom/offerModal/index.tsx
  components/chat/chatRoom/userOut/index.tsx
  components/chat/chatRoom/viewer/index.tsx
  components/common/sheetsButtons/simpleBorderButton/index.tsx
  components/roomInfo/footer/index.tsx
  hooks/useChatConnection.ts
  hooks/useRoomConnection.ts
  types/chat/chatRoom/types.ts
Labels: fix, refactor

#262 ✨ feat : userId parameter 추가 pr
  api/chat/api.ts
  api/chat/query.ts
  api/chat/serverApi.ts
  components/chat/chatRoom/sender/index.tsx
  components/common/catchComponent/index.tsx
  components/roomInfo/footer/index.tsx
  hooks/useRoomConnection.ts
Labels: fix

#264 ✨ feat : 채팅방에서 결제하기 버튼 누르면 recoil이랑 결제 정보 넘기기 #263 pr
  app/chat/page.tsx
  app/order/[id]/page.tsx
  atoms/chat/chatContentAtom.ts
  components/chat/chatList/control/index.tsx
  components/chat/chatList/modalControl/index.tsx
  components/chat/chatList/viewer/index.tsx
  components/chat/chatList/wrapper/index.tsx
  components/chat/chatRoom/approveMessage/index.tsx
  components/roomInfo/footer/index.tsx
  hooks/useRoomConnection.ts
Labels: fix, feat

#266 ✨ feat : 로그인 안한 유저가 접근하면 다른 화면 보여주기 #265 pr
  components/chat/chatList/viewer/index.tsx
  components/chat/headWrapper/index.tsx
  components/roomInfo/footer/index.tsx
  hooks/useRoomConnection.ts
Labels: feat

#267 ✨ feat : 캐치특가 컴포넌트 및 상세페이지 찜버튼 활성화
  api/room-info/api.ts
  api/room-info/query.ts
  components/common/catchComponent/index.tsx
  components/home/catch/catchItem/index.tsx
  components/roomInfo/body/navbarSection/page/accRegion/index.tsx
  components/roomInfo/body/navbarSection/page/roomInfo/index.tsx
  components/roomInfo/body/roomImage/index.tsx
  components/roomInfo/header/index.tsx
  components/roomInfo/header/rightButton/index.tsx
  types/common/heartButton/types.ts
Labels: feat, refactor

#270 Feature/#250
  app/order/complete/[id]/page.tsx
  app/order/complete/detail/page.tsx
  components/common/checkBox/index.tsx
  components/complete/completeMessage/index.tsx
  components/complete/navButton/index.tsx
  components/complete/productDetails/index.tsx
  components/complete/reservationInfo/index.tsx
  components/detail/ReservationDetail/index.tsx
  components/detail/ReservationSummary/index.tsx
  components/order/bookingHolderInfo/index.tsx
  components/order/guestInfo/index.tsx
  components/order/infoBox/index.tsx
  components/order/modal/actionButton/index.tsx
  components/order/modal/bookingDetails/index.tsx
  components/order/modal/disclaimer/index.tsx
  components/order/modal/index.tsx
  components/order/paymentButton/index.tsx
  components/order/paymentInfo/index.tsx
  components/order/paymentMethods/index.tsx
  components/order/productDetails/index.tsx
  components/order/termsAndConditions/index.tsx
  public/svg/Yanolja_CI 1.svg
  public/svgComponent/infoCircle.tsx
  utils/formatDate.ts
  utils/roundToTenWon.ts
Labels: feat, style

#271 🎨 style: 문구추가
  components/detail/ReservationSummary/index.tsx
Labels: style

#272 feature : QA 테스트 오류 수정
  components/common/bottomSheetsWithOutCloseBtn/index.tsx
  components/common/header/index.tsx
  components/common/sheetsButtons/moreButton/index.tsx
  components/home/searchBar/index.tsx
  components/roomInfo/header/index.tsx
  components/sale/bottomSheetsContent/fromSeller/index.tsx
  components/sale/catch/catchContainer/index.tsx
  components/sale/checkboxContainer/index.tsx
  components/sale/saleInfoContainer/index.tsx
  components/sale/sellingPrice/sellingPriceContainer/index.tsx
  utils/get-number-with-rounds.ts
Labels: fix

#274 ✨ feat: 로그인 안한 유저가 채팅방 들어왔을 때 보여주는 페이지 제작 #268 pr
  app/mypage/dashboard/conditions/consent-essential/page.tsx
  app/mypage/dashboard/conditions/consent-options/page.tsx
  app/mypage/dashboard/conditions/consent-third/page.tsx
  app/user-chat-login/layout.tsx
  app/user-chat-login/page.tsx
  components/chat/chatList/control/index.tsx
  components/chat/chatList/viewer/index.tsx
  components/chat/headWrapper/index.tsx
  components/chat/skeleton/index.tsx
  components/common/catchComponent/index.tsx
  components/home/review/reviewItem/index.tsx
  components/sale/saleInfoContainer/index.tsx
  hooks/useRoomConnection.ts
  middleware.ts
  package-lock.json
  package.json
  public/svgComponent/xSymbol.tsx
Labels: fix, feat

#278 🐛 fix : 달력 기본값 옵션 추가 및 QA 2차 개선
  components/sale/catch/catchContainer/index.tsx
  components/sale/saleEndContainer/index.tsx
Labels: fix, chore

#280 ✨ feat : 마이 페이지 기한 수정 기능 추가
  components/mypage/items/sellingItems/index.tsx
Labels: feat

#281 ✨ feat : kakao API 숙소용 지도 적용 완료
  components/roomInfo/body/navbarSection/page/accRegion/index.tsx
  components/roomInfo/body/navbarSection/page/accRegion/roomMap/index.tsx
Labels: feat, style

#283 🎨 style : 푸터 마진 수정
  components/common/footer/index.tsx
Labels: style

#284 ♻️ refactor : 마이페이지 리펙토링 #282 pr
  app/mypage/dashboard/sales/page.tsx
  app/mypage/page.tsx
  atoms/mypage/menuAtom.ts
  components/chat/chatRoom/productInfo/index.tsx
  components/common/sheetsButtons/borderButton/index.tsx
  components/mypage/account/accountButton/index.tsx
  components/mypage/account/accountContainer/index.tsx
  components/mypage/banner/bannerContainer/index.tsx
  components/mypage/banner/bannerItem/index.tsx
  components/mypage/divideWrapper/index.tsx
  components/mypage/divider/index.tsx
  components/mypage/divider/wishListDivider/index.tsx
  components/mypage/form/bankForm/index.tsx
  components/mypage/form/formInput/index.tsx
  components/mypage/form/profileForm/index.tsx
  components/mypage/form/withdrawForm/index.tsx
  components/mypage/header/index.tsx
  components/mypage/items/deleteButtons/index.tsx
  components/mypage/items/reEnrollButton/index.tsx
  components/mypage/items/sellingItems/index.tsx
  components/mypage/logout/index.tsx
  components/mypage/privacy/privacyToggle/index.tsx
  components/mypage/profile/profileButton/index.tsx
  constants/mypage.ts
  tailwind.config.ts
  tests/login.spec.ts
  tests/signUp.spec.ts
  types/chat/chatRoom/types.ts
  types/mypage/types.ts
  utils/get-dot-date.ts
  utils/mypage-utils.ts
Labels: fix, feat, refactor

#291 🎨 style : 메인 홈 반응형 적용
  app/home/page.tsx
  components/common/footer/index.tsx
  components/home/catch/catchContainer/index.tsx
  components/home/catch/catchItem/index.tsx
  components/home/catch/catchSkeletonUI/index.tsx
  components/home/header/index.tsx
  components/home/review/reviewContainer/index.tsx
  components/home/review/reviewItem/index.tsx
  components/home/searchBar/index.tsx
  public/svgComponent/logo.tsx
Labels: style

#293 ✨ feat: 마이페이지 라우팅 수정 및 채팅페이지 리펙토링 수정 반영 #292 pr
  api/chat/api.ts
  api/chat/query.ts
  app/chat/layout.tsx
  app/mypage/dashboard/loading.tsx
  atoms/mypage/mypageRoutingAtom.ts
  components/chat/chatItem/index.tsx
  components/chat/chatList/viewer/index.tsx
  components/chat/chatRoom/messageItem/index.tsx
  components/chat/headWrapper/index.tsx
  components/chat/header/index.tsx
  components/common/header/index.tsx
  components/common/sheetsButtons/simpleBorderButton/index.tsx
  components/common/sheetsButtons/simpleButton/index.tsx
  components/mypage/header/index.tsx
  components/mypage/items/sellingItems/index.tsx
  components/roomInfo/footer/index.tsx
  tailwind.config.ts
Labels: fix, feat, refactor

#294 fix : 무한스크롤 이슈 해결 및 검색화면 버튼 QA 이슈 해결
  api/deadline-items/api.ts
  atoms/deadlineItems/totalSizeAtom.ts
  components/catchItems/header/bottomHeader/index.tsx
  components/catchItems/items/index.tsx
  components/common/catchComponent/index.tsx
  components/common/searchBtmSheets/region/index.tsx
  components/common/spinner/index.tsx
  components/roomInfo/body/navbarSection/page/accRegion/roomMap/index.tsx
  components/searchroom/bodyComponent/index.tsx
  components/searchroom/bodyComponent/searchComponent/confirmBtn/index.tsx
  components/searchroom/bodyComponent/searchComponent/index.tsx
Labels: feat, refactor

#296 ✨ Feature/#295 pwa pr
  .gitignore
  README.md
  app/layout.tsx
  components/chat/chatItem/index.test.tsx
  components/chat/chatItem/index.tsx
  next.config.js
  package-lock.json
  package.json
  public/icons/apple-touch-icon.png
  public/icons/favicon.ico
  public/logo16x16.png
  public/logo192x192.png
  public/logo32x32.png
  public/logo512x512.png
  public/manifest.json
  tests/sales.spec.ts
Labels: chore

#297 ✨ feat: 검색결과 리스트 페이지에 무한스크롤 적용
  api/search-result/api.ts
  api/search-result/query.ts
  app/search-result/(noSortBtn)/map/page.tsx
  app/search-result/(sortBtn)/list/page.tsx
  components/search-result/list/accommodationList/index.tsx
  components/search-result/map/catchSpecialComponentWrapper/index.tsx
Labels: feat

#303 ✨feat : 판매 반응형 구현
  app/home/page.tsx
  app/sale/page.tsx
  components/common/checkInDateComponent/index.tsx
  components/common/footer/index.tsx
  components/home/bottomsheetContent/saleItems/index.tsx
  components/home/catch/catchContainer/index.tsx
  components/home/catch/catchItem/index.tsx
  components/home/catch/catchSkeletonUI/index.tsx
  components/home/header/index.tsx
  components/home/review/ReviewSkeletonUI/index.tsx
  components/home/review/reviewContainer/index.tsx
  components/home/review/reviewItem/index.tsx
  components/home/searchBar/index.tsx
  components/sale/catch/catchContainer/index.tsx
  components/sale/saleEndContainer/index.tsx
  components/sale/saleInfoContainer/index.tsx
  components/sale/saleInfoContainer/saleInfoSkeletonUI.tsx
  components/sale/sellingPrice/sellingPriceContainer/index.tsx
Labels: fix, style

#304 🎨 style : 반응형 적용 및 세부 디자인 수정
  components/catchItems/header/bottomHeader/index.tsx
  components/catchItems/header/middleHeader/index.tsx
  components/common/catchComponent/index.tsx
  components/common/checkInDateComponent/index.tsx
  components/common/heartButton/index.test.tsx
  components/common/heartButton/index.tsx
  components/common/searchBtmSheets/calendar/index.tsx
  components/common/searchBtmSheets/customer/index.tsx
  components/common/searchBtmSheets/region/index.tsx
  components/common/searchBtmSheets/room/index.tsx
  components/common/sheetsButtons/dropdownButton/index.tsx
  components/common/sheetsButtons/saleButton/index.tsx
  components/common/weekCalendar/index.tsx
  components/home/catch/catchContainer/index.tsx
  components/home/catch/catchItem/index.tsx
  components/home/deadLineItems/index.tsx
  public/svgComponent/fullHeart.tsx
  tailwind.config.ts
Labels: test, style, refactor

#307 ✨ feat: 검색 결과 수정, 검색 결과 스켈레톤ui 추가
  app/search-result/(noSortBtn)/map/page.tsx
  app/search-result/(sortBtn)/list/page.tsx
  components/order/guestInfo/index.tsx
  components/search-result/filterBar/index.tsx
  components/search-result/list/accommodationList/index.tsx
  components/search-result/list/listSkeletonUI/index.tsx
  components/search-result/list/productListControls/index.tsx
  components/search-result/map/catchSpecialComponentWrapper/index.tsx
  components/search-result/map/index.tsx
  components/search-result/map/toggleViewButtonWrapper/index.tsx
  components/search-result/toggleViewButton/index.tsx
Labels: feat, style

#309 🎨 style : 검색필터 버튼 재정렬
  components/common/sheetsButtons/dropdownButton/index.tsx
Labels: fix, style

#315 ✨ feat: 구매자 닉네임 추가, 금액수정
  app/order/complete/[id]/page.tsx
Labels: feat

#301 🧪 test : 채팅 페이지내 메시지 컴포넌트 테스트 코드 작성
  components/chat/chatRoom/declineMessage/index.test.tsx
  components/chat/chatRoom/messageItem/index.test.tsx
  components/chat/chatRoom/offerMessage/index.test.tsx
Labels: test

#318 ✨ feat: 결제완료 금액변경, 스켈레톤추가
  app/order/complete/[id]/page.tsx
  components/complete/completeSkeletonUI/index.tsx
Labels: feat, style

#320 ✨ feat: order 스켈레톤 추가
  app/order/[id]/page.tsx
  components/common/header/index.tsx
  components/complete/completeSkeletonUI/index.tsx
  components/order/orderSkeletonUI/index.tsx
Labels: style
